FROM jupyter/scipy-notebook:latest
MAINTAINER Matthias Hochsteger <matthias.hochsteger@tuwien.ac.at>

USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get -y install cmake git g++ patch
RUN apt-get update && apt-get -y install liboce-ocaf-dev libsuitesparse-dev zip libcgns-dev libhdf5-dev intel-mkl openmpi-bin libopenmpi-dev libopenblas64-dev
RUN /opt/conda/bin/pip pip install webgui_jupyter_widgets mpi4py batchspawner
RUN cd && git clone https://github.com/ngsolve/ngsolve.git
RUN cd ~/ngsolve && git submodule update --init --recursive
RUN cd ~/ngsolve && mkdir build && cd build && cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/opt/conda \
  -DMPI4PY_INCLUDE_DIR=/opt/conda/lib/python3.9/site-packages/mpi4py/include/mpi4py \
  -DENABLE_UNIT_TESTS=OFF \
  -DINSTALL_PROFILES=OFF \
  -DBUILD_STUB_FILES=OFF \
  -DNG_INSTALL_DIR_INCLUDE=include/netgen \
  -DNG_INSTALL_DIR_LIB=lib/netgen \
  -DUSE_CCACHE=OFF \
  -DUSE_CGNS=ON \
  -DUSE_GUI=OFF \
  -DUSE_GUI=OFF \
  -DUSE_HYPRE=OFF \
  -DUSE_MKL=ON \
  -DMKL_LIBRARY=/usr/lib/x86_64-linux-gnu/libmkl_rt.so \
  -DMKL_INCLUDE_DIR:PATH=/usr/include/mkl \
  -DUSE_MPI=ON \
  -DUSE_MUMPS=OFF \
  -DUSE_NATIVE_ARCH=ON \
  -DUSE_OCC=ON \
  -DUSE_UMFPACK=ON

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/lib
RUN cd ~/ngsolve/build && make -j install

RUN jupyter nbextension install webgui_jupyter_widgets --py --sys-prefix
RUN jupyter nbextension enable webgui_jupyter_widgets --py --sys-prefix

# Switch back to jovyan to avoid accidental container runs as root
USER ${NB_UID}
